sonata_admin:
    title: 'GBC ADMINISTRATION'
    dashboard:
        blocks:
        groups:

          Agenda:
                on_top:               true
                label:                'Agenda'
                icon:                 '<i class="fa blue fa-calendar menu-item-icon"></i>'
                label_catalogue: ~
                items:
                      - admin.agenda



          Projet:
                label:                ~
                icon:                 '<i class="fa blue fa-briefcase menu-item-icon"></i>'
                label_catalogue: ~
                items:
                    - route:          admin_app_projet_create
                      label:          'Ajouter Projet'
                    - route:          admin_app_projet_list
                      label:          'Lister Projets'
          Client:
                label:                ~
                icon:                 '<i class="fa fa-user menu-item-icon-client menu-item-icon"></i>'
                label_catalogue:      ~
                items:
                    - route:          admin_app_client_create
                      label:          'Ajouter Client'
                    - route:          admin_app_client_list
                      label:          'Lister Projets'

          Facture:
                label:                ~
                icon:                 '<i class="fa fa-file menu-item-icon"></i>'
                label_catalogue:      ~
                items:
                    - route:          admin_app_facture_create
                      label:          'Ajouter Facture'
                    - route:          admin_app_facture_list
                      label:          'Lister Factures'

          Service:
                label:                ~
                icon:                 '<i class="fa fa-cogs menu-item-icon"></i>'
                label_catalogue:      ~
                items:
                    - route:          admin_app_service_create
                      label:          'Ajouter Service'
                    - route:          admin_app_service_list
                      label:          'Lister Services'

          Metier:
                label:                ~
                icon:                 '<i class="fa fa-building menu-item-icon"></i>'
                label_catalogue:      ~
                items:
                    - route:          admin_app_metier_create
                      label:          'Ajouter Metier'
                    - route:          admin_app_metier_list
                      label:          'Lister Metiers'

          Tache:
                label:                ~
                icon:                 '<i class="fa fa-tasks menu-item-icon"></i>'
                label_catalogue:      ~
                items:
                    - route:          admin_app_tache_create
                      label:          'Ajouter Tache'
                    - route:          admin_app_tache_list
                      label:          'Lister Taches'

          Employee:
                label:                ~
                icon:                 '<i class="fa fa-user menu-item-icon"></i>'
                label_catalogue:      ~
                items:
                    - route:          admin_app_user_create
                      label:          'Ajouter Employee'
                    - route:          admin_app_user_list
                      label:          'Lister Employees'



    assets:
          extra_javascripts:
              - dependencies/fullcalendar/core/main.js
              - dependencies/fullcalendar/bootstrap/main.js
              - dependencies/fullcalendar/daygrid/main.js
              - dependencies/fullcalendar/interaction/main.js
              - dependencies/fullcalendar/timegrid/main.js
              - dependencies/axios/axios.js
              - assets/js/helpers.js
              - assets/js/fetchers.js
              - assets/js/fullcalendar.js

          extra_stylesheets:
              - bundles/sonatatranslation/css/sonata-translation.css
              - build/app.css
              - dependencies/fullcalendar/bootstrap/main.css
              - dependencies/fullcalendar/core/main.css
              - dependencies/fullcalendar/daygrid/main.css
              - dependencies/fullcalendar/timegrid/main.css





sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        admin.block.service.dashboard: ~
        admin.block.service.agenda: ~


